server:
  port: 8899

  tomcat:
    max-threads: 1024
    accept-count: 512
    accesslog:
      buffered: true # Buffer output such that it is only flushed periodically.
      directory: /tmp/logs/auth-service # Directory in which log files are created. Can be relative to the tomcat base dir or absolute.
      enabled: true # Enable access log.
      file-date-format: .yyyy-MM-dd # Date format to place in log file name.
      pattern: '%a %l %t %r %s %D %b' # Format pattern for access logs.
      prefix: tomcat_access_log # Log file name prefix.
      rename-on-rotate: false # Defer inclusion of the date stamp in the file name until rotate time.
      request-attributes-enabled: false # Set request attributes for IP address, Hostname, protocol and port used for the request.
      rotate: true # Enable access log rotation.
      suffix: .log # Log file name suffix.

#数据库连接配置
spring:
  application:
    name: auth-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.0.14:3306/test?characterEncoding=UTF-8
    username: orion
    password: orion2018
    #hikari
    hikari.connection-timeout: 3000
    hikari.maximum-pool-size: 100

  redis:
    database: 1  #Redis索引0~15，默认为0
    host: 172.16.0.29
    port: 6379
    password:  #密码（默认为空）
    lettuce: # 这里标明使用lettuce配置
      pool:
        max-active: 8   #连接池最大连接数（使用负值表示没有限制）
        max-wait: 5000ms  #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 5     #连接池中的最大空闲连接
        min-idle: 0     #连接池中的最小空闲连接
    timeout: 3000ms    #连接超时时间（毫秒）

#eureka服务配置
#eureka:
#  client:
#    service-url:
#      defaultZone: http://admin:eureka-test2019@172.16.0.2:8761/eureka/,http://admin:eureka-test2019@172.16.0.33:8761/eureka/

mybatis:
  typeAliasesPackage: com.xuelin.coke.domain.**
  mapperLocations: classpath:mapper/*.xml

